# Generated by Django 4.1.3 on 2022-12-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='img_url',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
